# Generated by Django 4.1.6 on 2023-02-12 16:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 12, 21, 37, 11, 800660)
                    ),
                ),
                ("no_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
