# Generated by Django 4.1.6 on 2023-02-14 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_likepost_alter_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="id_user",),
        migrations.AlterField(
            model_name="likepost",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.post"
            ),
        ),
        migrations.AlterField(
            model_name="likepost",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 14, 19, 20, 19, 945216)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
