# Generated by Django 4.1.6 on 2023-02-14 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_profile_id_user_alter_likepost_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 14, 19, 29, 35, 772618)
            ),
        ),
    ]
