# Generated by Django 4.2.2 on 2023-12-19 12:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 19, 18, 16, 51, 934312)
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 19, 18, 16, 51, 932314)
            ),
        ),
    ]
